config/routes.rb
TodoList::Application.routes.draw do
  resources :to_do_lists
  root 'to_do_lists#index'

end

app/models/to_do_list.rb
class ToDoList < ActiveRecord::Base

	validates :title, presence: true 
	validates :title, length: { minimum: 3 }
	validates :description, presence: true
	validates :description, length: { minimum: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/to_do_lists_controller.rb
class ToDoListsController < ApplicationController
  before_action :set_to_do_list, only: [:show, :edit, :update, :destroy]

  # GET /to_do_lists
  # GET /to_do_lists.json
  def index
    @to_do_lists = ToDoList.all
  end

  # GET /to_do_lists/1
  # GET /to_do_lists/1.json
  def show
  end

  # GET /to_do_lists/new
  def new
    @to_do_list = ToDoList.new
  end

  # GET /to_do_lists/1/edit
  def edit
  end

  # POST /to_do_lists
  # POST /to_do_lists.json
  def create
    @to_do_list = ToDoList.new(to_do_list_params)

    respond_to do |format|
      if @to_do_list.save
        format.html { redirect_to @to_do_list, notice: 'To do list was successfully created.' }
        format.json { render action: 'show', status: :created, location: @to_do_list }
      else
        format.html { render action: 'new' }
        format.json { render json: @to_do_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /to_do_lists/1
  # PATCH/PUT /to_do_lists/1.json
  def update
    respond_to do |format|
      if @to_do_list.update(to_do_list_params)
        format.html { redirect_to @to_do_list, notice: 'To do list was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @to_do_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /to_do_lists/1
  # DELETE /to_do_lists/1.json
  def destroy
    @to_do_list.destroy
    respond_to do |format|
      format.html { redirect_to to_do_lists_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_to_do_list
      @to_do_list = ToDoList.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def to_do_list_params
      params.require(:to_do_list).permit(:title, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/to_do_lists_helper.rb
module ToDoListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TodoList</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/to_do_lists/_form.html.erb
<%= form_for(@to_do_list) do |f| %>
  <% if @to_do_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@to_do_list.errors.count, "error") %> prohibited this to_do_list from being saved:</h2>

      <ul>
      <% @to_do_list.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/to_do_lists/edit.html.erb
<h1>Editing to_do_list</h1>

<%= render 'form' %>

<%= link_to 'Show', @to_do_list %> |
<%= link_to 'Back', to_do_lists_path %>

app/views/to_do_lists/index.html.erb
<h1>Listing to_do_lists</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @to_do_lists.each do |to_do_list| %>
      <tr id="<%= dom_id(to_do_list) %>">
        <td><%= to_do_list.title %></td>
        <td><%= to_do_list.description %></td>
        <td><%= link_to 'Show', to_do_list %></td>
        <td><%= link_to 'Edit', edit_to_do_list_path(to_do_list) %></td>
        <td><%= link_to 'Destroy', to_do_list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New To do list', new_to_do_list_path %>

app/views/to_do_lists/new.html.erb
<h1>New to_do_list</h1>

<%= render 'form' %>

<%= link_to 'Back', to_do_lists_path %>

app/views/to_do_lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @to_do_list.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @to_do_list.description %>
</p>

<%= link_to 'Edit', edit_to_do_list_path(@to_do_list) %> |
<%= link_to 'Back', to_do_lists_path %>